NativeScript/nativescript-dev-webpack

index.js
resource-resolver-plugins/StyleUrlResolvePlugin.js
webpack.common.js.angular.template

When given an url "./style.css" and the resource "style.css" does not
exist in the current directory, the plugin will change the url to
"style.android|ios.css". The target platform should be provided in the
options of the plugin.
Closes #36

Feat: add plugin to support android/ios styleUrls

---

index.js
postinstall.js

Required for the StyleUrlResolvePlugin

fix: add typescript@~2.0.10 to ng projects

---

postinstall.js
tsconfig.aot.json.template

Angular-compiler requires the `paths` option set in `tsconfig` in order to resolve modules of the type `ui/page`, `ui/frame`, `platform`, etc. The `paths` option is available in Typescript ^2.1. 
This should be released when the NativeScript platforms' support for Typescript@2.1 is released (`NativeScript@2.5`).

feat: add support for tsc@2.1 and ng@2.4

---

tns-xml-loader.js
webpack.common.js.angular.template

Make the tns-xml-loader parse Angular templates from TypeScript files.
fixes #55

fix: register elements from embedded templates

---

index.js

Fixes tap gesture not working when using uglify.

Exclude from mangling classes inheriting from Android native types.

---

index.js

Uglify shouldn't mangle the TextBase descendant classes.
fixes https://github.com/NativeScript/sample-Groceries/pull/202

fix: exclude from mangling EditableTextBase

---

installer.js
nativescript-target/NsNodeGlobalsPlugin.js
nativescript-target/index.js
webpack.common.js.angular.template
webpack.common.js.nativescript.template

Add NodeGlobalsPlugin to prevent webpack from overriding the global property.

feat(deps): add support for webpack 2.2+

---

tns-xml-loader.js
webpack.common.js.angular.template

This is needed due to changes in the behaviour of `@ngtools/webpack` v1.2.4.
Also a little change in the template extraction from `ts` component.
fixes #64

fix: run `tns-xml-loader` before `@ngtools` loader

---

package.json
tsconfig.aot.json.template

Reuse tsconfig.json from the client project. Force as few TS options as possible.
Also removes the need to have matching `"lib"` settings and allows us to build tns-core-modules@3.0.0 projects.

Extend existing tsconfig

---

webpack.common.js.angular.template
webpack.common.js.nativescript.template

Clashes with `everlive-sdk` plugin.
Closes #80

fix(templates): Disable node "fs" shim

---

bin/ns-bundle

Spawning child processes requires "shell: true" for windows.
Fixes https://github.com/NativeScript/NativeScript/issues/3715

fix(scripts): correctly execute ns-bundle for windows

---

bin/ns-bundle

Leaving old build files in the platform folders caused several issues.
fixes #75, fixes #112

fix(ns-bundle): use remove/add platform instead of clean-app

---

tsconfig.aot.json.template

The "exclude" property isn't properly inherited from the base
configuration ("tsconfig.json") so we need to explicitly specify it.
This caused the angular compiler to try to parse the `platforms` folder
and eventually fail.
fixes #101

fix(tsconfig): add "exclude" property to aot config

---

bin/ns-bundle

When spawning a child process, the arguments should be escape in order
to arguments with special chars (such as spaces) in them to work.
fixes #123

fix(ns-bundle): escape arguments passed to `tns` command

---

bin/ns-bundle

When this is released, developers will be able to prepare and bundle the project and then release it from xcode. This can be done with the following command:
`npm run ns-bundle --android/ios`
If you don't pass `--start-app` or `--build-app` to ns-bundle, the
project will be only prepared and bundled now.
Related to https://github.com/NativeScript/nativescript-cli/issues/2716, https://github.com/NativeScript/nativescript-cli/issues/2702

feat(ns-bundle): app can be just prepared and bundled now

---

webpack.common.js.angular.template
webpack.common.js.javascript.template
webpack.common.js.typescript.template

This is required for compatibility reasons (NativeScript 2.5).
When a non-webpacked NativeScript application is deployed to phone, the apk
contains a `tns-java-classes.js` file. If that file is present, it is
dynamically loaded by the Android runtime at startup.
Webpacked NativeScript applications didn't contain that file as it is
not needed. But when the application is deployed to phone, the previous
`tns-java-classes.js` file is not removed from the app folder on the
phone. That causes the Android runtime to try load the file and fail.
Since this commit, all webpacked NativeScript apps will be shipped with
an empty `tns-java-classes.js` file which is harmless and is used to
override the existing file left from previous deployment.
related to …

fix(template): ship bundle with empty `tns-java-classes.js` chunk

---

webpack.common.js.angular.template
webpack.common.js.javascript.template
webpack.common.js.typescript.template

NativeScript UI chart directives wasn't included in the bundle when webpacking. This change should fix the problem as the platform specific files are now preferred over the plain ones.
Here's a simple project that demonstrates the usage of chart with webpack: https://github.com/sis0k0/chart.
fixes #31, fixes https://github.com/telerik/nativescript-ui-feedback/issues/140

fix(template): include platform specific files in bundle first

---

index.js
webpack.common.js.angular.template
webpack.common.js.javascript.template
webpack.common.js.typescript.template

The tns-java-classes.js that is required for NativeScript 2.5 Android
builds is now create internally (GenerateStarterPlugin) instead as part
of CommonChunksPlugin.

fix(template): create empty `tns-java-classes.js` internally

---

templates/vendor-platform.android.ts.template

The `__requireOverride` hook in `vendor.android.js` seems to be redundant.

Remove redundant __requireOverride

---

prepublish/common/rules.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

When uglify is used, it triggers the minification option of the
css-loader. The css-loader uses internally cssnano to optimize the size
of the stylesheets. Since NativeScript supports only a subset of the CSS language, many of these optimizations may be damaging for the user's css.
Such is the case with `background-position`: center, which gets
translated to `background-position`: 50%, which is currently not working
in NativeScript 3.0 (https://github.com/NativeScript/NativeScript/issues/4201).
closes #135

fix(template): disable minification of css by css-loader

---

bin/ns-bundle

related to https://github.com/NativeScript/android-runtime/issues/759

fix(ns-bundle): clean android build for NativeScript CLI 3.0.1<=

---

bin/ns-bundle

Allows for using --publish-app along with --start-app, --build-app, etc.

fix(ns-bundle): parse all '*-app' flags as tns commands

---

installer.js
npmScriptsManager.js

fix(npm scripts): replace deprecated build-app script on postinstall

---

.travis.yml
build/prepublish-next.js

- add .travis.yml config
- add prepublish-next script

chore(travis): publish next version

---

bin/ns-bundle

fix(ns-bundle): remove command escaping when spawning child process

---

bin/ns-bundle

fix(ns-bundle): stop escaping command args twice

---

snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js
snapshot/android/utils.js

Avoid sending a https request to the `v8-versions.json` file per each build.
Instead, save the file locally and read it for official android runtime versions.

refactor: fetch V8 versions map from url or local file

---

prepublish/angular/imports.js
prepublish/angular/plugins.js
prepublish/angular/rules.js
templates/webpack.angular.js

- the tsconfig path is needed when worker scripts are transpiled

refactor(templates): specify tsconfig path for @ngtools/webpack loader

---

bin/update-ns-webpack
installer.js
npmScriptsManager.js
projectFilesManager.js
verify/update.js

The bin script can be used as before, but it has some additional flags:
`npm run update-ns-webpack --deps --scripts --configs`
- update dependencies (--deps)
- update npm scripts (--scripts)
- update webpack configuration files (--configs)
PS: First, you should add the following to the package.json:
```
"scripts": {
"update-ns-webpack": "update-ns-webpack"
}
// ...
```

refactor(update-ns-webpack): provide multiple options for updating the plugin

---

css2json-loader.js
package.json
plugins/PlatformFSPlugin.js
plugins/PlatformSuffixPlugin.js
plugins/index.js

The config can now be set to resolve .css files as:
```
module: {
rules: [
{ test: /\.html$|\.xml$/, loader: "raw-loader" },
{ test: /\.css$/, loader: "nativescript-dev-webpack/css2json-loader" }
]
}
```
This will use the parser from `tns-core-modules/css` to parse the CSS content and convert it to a module that exports a JSON. The JSON generated is quite verbose so times should be carefully measured on real devices whether it is better to use this approach. For example our CSS parser may be able to parse the CSS theme faster than the JS module is loaded parsed etc.
The PlatformSuffixPluing is used like:
```
const PlatformSuffixPlugin = require("nativescript-dev-webpack/PlatformSuffixPlugin");
// ...
resolve: {
plugins: [new PlatformSuffixPlugin(platform, ["ios", "android"])]
}
```
When a …

CSS loader parsing CSS to JSON, platform suffix resolver and platform file system plugins

---

index.js
plugins/NativeScriptSnapshotPlugin.js
projectHelpers.js
snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js

_problem_
nativescript-dev-webpack is not compatible with new android studio project template
_solution_
need to change bundle output path, depending on the android template version

refactor: update Android project path to support next runtime

---

bin/ns-bundle

When you have Node.js 9 installed, CLI prints a warning that support for this version is not verified. Our webpack plugin tries to get the version, but it receives the warning and decides the version is incorrect. So all scripts fail.
In order to resolve the issue, get all data send to the stdout of the spawned `tns --version` process and parse it.

fix(ns-bundle): support for Node.js 9

---

lib/after-prepare.js
lib/before-prepareJS.js
lib/utils.js
package.json
postinstall.js
prepublish/common/plugins.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

Instead of relying on npm scripts, rely on hooks so that certain parts of the prepare chain can be overriden.
Do not skip moving `App_Resources` directory, as CLI expects it to be present in platforms and will take care of the resources inside.
Merge along with https://github.com/NativeScript/nativescript-cli/pull/3116
Ping @rosen-vladimirov @sis0k0

feat: enable plugin to run through {N} CLI hooks

---

snapshot/android/utils.js

_problem_
Node 9.x WriteFileStream API is changed. [Read more here](https://github.com/nodejs/node/pull/15407).
_solution_
use new API that should be backward compatible.
fixes: https://github.com/NativeScript/nativescript-dev-webpack/issues/344

fix(snapshot): use autoclose option on writestream

---

demo/AngularApp/app/item/item-detail.component.ts
demo/AngularApp/app/item/items.component.ts
moduleid-compat-loader.js
templates/webpack.angular.js

The angular 5 framework will typecheck the moduleId is a string,
while in webpack scenarios the moduleId is ignored and relative paths
are handled by the angular compiler and the webpack loaders,
module.id is number and fails the typeschecks.
Implemented a loader that will strip the moduleId: module.id when
compiled with webpack, the moduleId: module.id is still necessary for development without webpack.
As a reminder if we manage to setup webpack for watch and debug,
we can recommend removing all moduleId: module.id occurences and delete the loader.

refactor: Refactor moduleId: __filename to moduleId: module.id

---

demo/AngularApp/app/ninjas/ninjas.component.ts
demo/AngularApp/app/ninjas/ninjas.routes.ts

It turns out the ./path for loadChildren have never worked as relative to the routes module,
and was always expected to be relative to app/ in non-webpack builds. Modifying the lazy loaded
ninjas to feature both ./ and ~/ paths relative to the app.

refactor: loadChildren to work with ~/path and ./path both relative to app/

---

lib/before-prepareJS.js
lib/compiler.js

When the webpack compiler fails, the error is not used in the rejection, so the promise is always rejected with `undefined`.
Fix this by respecting the error. Construct real error object as well.
Force rebuild of application when webpack is used  …
In case we want to use webpack, force the build by setting nativeChanged property of changesInfo to true.
This is TEMP solution until we have a better one.
Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/340

fix(compiler): reject promise with real error

---

dependencyManager.js
projectHelpers.js

Add sass dependency only if the dev-sass plugin is already installed.

feat(sass): add conditional sass deps for webpack

---

demo/AngularApp/app/app.module.ngfactory.d.ts
demo/AngularApp/app/main.aot.ts

The angular compiler will generate dynamically the app.module.ngfactory.d.ts.
For plain tsc to compile without errors the main.aot.ts should be compiled without errors,
so app.module.ngfactory.d.ts will provide the necessary type information.

refactor(angular5): Declare the app.module.ngfactory.d.ts generated by ngc with AoT

---

plugins/WatchStateLoggerPlugin.ts

When run with `webpack --watch` the WatchStateLoggerPlugin
will print console messages with the watcher state.
When run with `webpack` (no --watch) the WatchStateLoggerPlugin
will be silent in the console, but still notify via IPC.

refactor: Show watch state messages only when webpack is watching

---

templates/webpack.angular.js

Loading the .ts files for WebWorkers using the @ngtools/webpack requires
at least the tsConfigPath to be provided to the loader as options.

refactor: Add options to the @ngtools/webpack loaders for workers support

---

projectFilesManager.js
templates/tsconfig.aot.json
templates/webpack.angular.js

The angular compiler options inside tsconfig.aot.json are not needed for webpack compilation.

refactor: remove tsconfig.aot.json file

---

templates/webpack.angular.js
templates/webpack.typescript.js

Windows uses backslashes for paths. For app.css the path will be something like:
```
\\...\\projectName\\app\\app.css"
```
compared to *nix systems where the file path will be:
```
/.../projectName/app/app.css"
```
fixes #378

fix: respect windows paths in /app.css regex

---

plugins/NativeScriptAngularCompilerPlugin.ts

The compile host seems to use forward instead of backward slashes on windows.
fixes #376

fix: support aot on windows

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

When uglify is used, it triggers the minification option of the
css-loader. The css-loader uses internally cssnano to optimize the size
of the stylesheets. Since NativeScript supports only a subset of the CSS language, many of these optimizations may be damaging for the user's css.
related to #154, #135
fixes #377

fix(css): disable minification when using uglify

---

dependencyManager.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

feat: use UglifyJsPlugin which support es6 code

---

README.md
dependencyManager.js

The template that the project was created with should has that dependency.

refactor: stop adding TS as dependency

---

CONTRIBUTING.md
bin/ns-verify-bundle

- chore: deprecate ns-verify-bundle script as it's no longer used in CI
- docs: update Contributing guide

docs: update Contributing guide and deprecate old verify script

---

mangle-excludes.js

This should fix the issue:
```
JS: Warning: 't' is not supported when 'showOverNavigation' is set to 'true'.
```
Should be reverted after 4.0 release. See: https://github.com/telerik/nativescript-ui-feedback/issues/477#issuecomment-360772046
fixes #258

fix(uglify): prevent SideDrawer transition class names from being renamed

---

package.json
snapshot/android/utils.js

Use 'request' node package for https requests and 'proxy-lib' for getting configured proxy settings (see: https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/general/proxy-set.md).
fixes #389

fix(snapshot): use request module for http requests

---

lib/before-prepareJS.js
lib/before-watch.js
lib/before-watchPatterns.js
lib/compiler.js
lib/constants.js
package.json
plugins/WatchStateLoggerPlugin.ts
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

Plug into NativeScript CLI's LiveSync pipeline in order to enable incremental webpacking with watch.
Includes:
* Instruct CLI to watch `App_Resources` directory only
* Launch `webpack` with `--watch` on before-watch hook
* Do not launch multiple `webpack` processes
Merge after https://github.com/NativeScript/nativescript-cli/pull/3350
Implements https://github.com/NativeScript/nativescript-cli/issues/3349
Ping @sis0k0 @rosen-vladimirov @KristianDD

feat(livesync): enable webpack with watch

---

lib/before-watchPatterns.js

Need to send the arguments when we call the original method inside before-watchPatterns hook.

fix-next: send arguments in watchPatterns hook

---

lib/before-shouldPrepare.js
package.json

Consume `shouldPrepare` hook in order to control when CLI should prepare the project.
Project should be prepared every time webpack is invoked with different `env` options.
(e.g. first run was `tns run android --bundle` and the second run is `tns run android --bundle --env.uglify`)
Merge after https://github.com/NativeScript/nativescript-cli/pull/3399
Ping @rosen-vladimirov @sis0k0

feat: consume shouldprepare hook

---

lib/after-prepare.js
lib/before-prepareJS.js
lib/before-watch.js
lib/compiler.js
lib/utils.js

Allow snapshot only in release
Ping @sis0k0 @rosen-vladimirov

fix: allow snapshot only in release

---

plugins/GenerateBundleStarterPlugin.js

The starter assets shouldn't be emitted on each compilation cycle, when using webpack with watch. Instead they should be cached if possible.

fix-next: cache package.json, starter.js and tns-java-classes.js between compilations

---

bin/ns-verify-bundle
index.js
installer.js
lib/before-prepareJS.js
lib/before-watchPatterns.js
lib/compiler.js
lib/constants.js
lib/utils.js
projectHelpers.js
snapshot/android/utils.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
verify/update.js

depends on https://github.com/NativeScript/nativescript-cli/pull/3423

refactor: use webpack context when notifying CLI for changed files

---

lib/compiler.js

Remove progress indication as `webpack` [prints said indication on the `stderr`](https://github.com/webpack/webpack/blob/4428efe48e1c5ff4cadb79e13f0fa48c12bdac35/lib/ProgressPlugin.js#L50) which confuses some tools
Ping @sis0k0

fix: remove progress indication

---

dependencyManager.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

Every time we are running a new build with webpack the platforms/.../app/ dir should be deleted as there may be old assets
left.
Ex.
When the app bundled with snapshot enabled:
```
tns build android --bundle --env.snapshot
```
this produces some assets:
```
platforms/android/.../app/vendor.js
platforms/android/.../app/_embedded_script.js
// ...
```
Then, if the project is bundled without snapshot:
```
tns build android --bundle
```
the produced assets will override the ones that are already in
`platforms/android/.../app`. However, since the build is without
snapshot, an `_embedded_script.js` won't be generated to override the one
that's left in `platforms/android/.../app` from the previous build.
We'll be using `CleanWebpackPlugin` to clean the dist folder.
**_Important_**: Currently …

fix(prepare): clean platforms/.../app/ when running webpack

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

When building for Android the App_Resources for iOS should not be copied to the dist directory and vice-versa.
Rebased on top of https://github.com/NativeScript/nativescript-dev-webpack/pull/466

fix-next: copy only the target platform App Resources

---

index.js

Export an empty array for `uglifyMangleExcludes` to prevent crashes when using older webpack configurations.
related to #461

fix-next: export uglifyMangleExcludes for backwards compatibility

---

lib/utils.js

This excessive comma provokes some strange behavior on nodejs 6 and the file cannot be `require`d.
Ping @sis0k0

fix: remove unnecessary comma

---

nsCliHelpers.js

The plugin should fall back to using some default project settings (`appPath: 'app'`, `appResourcesPath: 'app/App_Resources'`) if {N} CLI is not globally installed.
Steps to test:
1. Create new {N} project:
```
tns create my-project
cd my-project
```
2. Uninstall {N} CLI:
```
npm uninstall -g nativescript
```
> If you're using nvm it wouble be enough to set up an empty workspace by installing a new node version. For example - `nvm install 9.9.0`.
3. Install `nativescript-dev-webpack` from the current PR's branch:
```
npm i nativescript/nativescript-dev-webpack#sis0k0/return-if-no-tns
```
**Expected behaviour**
The plugin should be installed successfully and `vendor.ts`, `vendor-platform.android.ts` and `vendor-platform.ios.ts` should be added inside the app/ dir.
**Current behaviour**
The …

fix-next(nsCliHelpers): return undefined if no global CLI

---

lib/after-prepare.js
lib/before-prepareJS.js
lib/before-watch.js
lib/before-watchPatterns.js

When CLI is used as a library, the `$projectData` is not populated. Instead of using this injected dependency in the hooks, the projectData should be taken from the hookArgs or from the `projectDataService`.
Fix all hooks, so the correct projectData is used.
Trying to use webpack builds from CLI, when CLI is used as a library, leads to different errors as the projectData is not correct.
The hooks take the correct data from hookArgs or projectDataService and the build with webpack works when CLI is used as a library

fix: Hooks are not executed correctly when CLI is used as a library

---

lib/before-cleanApp.js
lib/before-prepareJS.js
lib/before-shouldPrepare.js
lib/before-watch.js

In a long living process, where the project can be changed, we need to set
the INIT_CWD environment variable in all before-* hooks. Currently it is
set only in the `before-watchPatterns` hook. This way, when we use webpack
for a project and later we try to use webpack for another project, we try
to execute some operations based on the INIT_CWD directory, which still
points to our old project. In order to fix this unexpected behavior, set
the INIT_CWD in all before-* hooks, as some of them may be skipped based
on the state of the project.
Currently when you try to use webpack to build more than one project in the same process (for example in Sidekick), the INIT_CWD variable is set when the first project is built. When the next project should be build, the INIT_CWD env variable is already …

fix: Set INIT_CWD env in all before-* hooks

---

postinstall.js
projectFilesManager.js

Compare current webpack.config.js and the one that will come from the installing version of nativescript-dev-webpack plugin and in case when they are different print a warning message.
- [x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
When the user has a project with already generated `webpack.config.js` and update `nativescript-dev-webpack` plugin to newer version, `webpack.config.js` is not replaced and this way if the newer version of `nativescript-dev-webpack` has changes in `webpack.config.js` file they are not respected in user project.
When the user has a project with already generated `webpack.config.js` and update `nativescript-dev-webpack` plugin to newer version which has changes in …

Compare webpack.config files

---

CHANGELOG.md
CONTRIBUTING.md
nsCliHelpers.js
package.json

Should be merged with `rebase and merge`.

chore: add changelog for the 0.10.0 release and steps for publishing

---

package.json

Update nativescript-hook to 0.2.4. Release notes: https://github.com/NativeScript/nativescript-hook/releases/tag/v0.2.4
In case you have hooks already installed, but you delete your node_modules, calling `npm install` will execute postinstall scripts of the packages and you'll see messages like:
```
Hook already installed: nativescript-dev-webpack
```
This message does not give enough information for the location of the hook.
In case you have hooks already installed, but you delete your node_modules, calling `npm install` will execute postinstall scripts of the packages and you'll see messages like:
```
Hook already installed: nativescript-dev-webpack at location `<project dir>/hooks/before-prepareJs`
```

chore: update dependency - nativescript-hook

---

lib/before-cleanApp.js
lib/before-prepareJS.js
lib/before-shouldPrepare.js
lib/before-watch.js
lib/before-watchPatterns.js
lib/utils.js

Previously the INIT_CWD environment variable was set only in one of the hooks. In a recent PR, we've changed the logic of all `before-*` hooks to set the INIT_CWD environment variable.
After some discussions and investigation, we've found that we do not need the INIT_CWD variable. So remove the setting of the variable from all hooks and delete the method that sets it.
Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/494.

fix(hooks): Do not set INIT_CWD on any hook

---

index.js
plugins/NativeScriptAngularCompilerPlugin.ts
plugins/angular.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

Currently when the plugin is used with symlink, the execution fails as the project dir is calculated incorrectly. Instead of trying to find the project dir, pass it wherever it is required.
This leads to changes in the way NativeScriptAngularCompilerPlugin is loaded - currently it uses the projectDir directly when the plugin is loaded. However, at this point we do no know the exact location of the project directory.
So change the require of the NativeScriptAngularCompilerPlugin to return a function, which accepts projectDir as argument. Expose the loading through a new method in the nativescript-dev-webpack plugin - `loadAdditionalPlugins`.
Currently the plugin cannot be used as symlink, as the projectDirectory is calculated incorrectly.
The projectDirectory is not calculated - we know it …

fix: Allow using the plugin via symlink

---

templates/webpack.angular.js

- the webpack build is now following the symLinks in Angular apps
- the root node_modules folder of the app now takes precedence over the local node_modules during module resolution (avoiding duplicate modules in the bundle when following symLinks) 
When you try to build the Angular demo of a plugin and the plugin source is linked in the demo, you will receive the following exception:
> Error: ...`demo-angular/node_modules/nativescript-your-plugin/your-plugin.ts` is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. TS files in published libraries are often a sign of a badly packaged …

fix: bundling of Angular apps using linked TS plugins

---

plugins/NativeScriptSnapshotPlugin/index.js
plugins/NativeScriptSnapshotPlugin/options.json

v8Version which will be used for snapshot generation can be passed now to NativeScriptSnapshotPlugin options

feat: configure v8Version for snapshot tools

---

CHANGELOG.md
package.json

[Changelog](https://github.com/NativeScript/nativescript-dev-webpack/blob/dc0617809ebe3876313ac287f85d2ede482d9d1e/CHANGELOG.md).

release: cut the 0.11.0 release

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

feat: move all node modules to the common chunk

---

androidProjectHelpers.js
index.js
plugins/NativeScriptSnapshotPlugin/index.js
projectHelpers.js
snapshot/android/project-snapshot-generator.js

The plugin now works with 4.0+, so the logic for lower versions of the
android runtime is no longer needed.

refactor: remove android-runtime 3.4< specific code

---

lib/utils.js

This can't be parsed with node 6.

fix-next: remove extra comma on Object.assign

---

templates/webpack.typescript.js

If you use a linked plugin with node_modules, the core modules will be included twice in the bundle and the app will crash. 
If you use a linked plugin with node_modules, the core modules will be included only once from the node_modules in the root folder of the app.

fix: bundling of ts apps using linked plugins

---

lib/before-cleanApp.js

Fixes the case when the user executes the following commands:
tns run android --bundle --release --env.snapshot
tns run android --bundle
Does not work the following commands:
tns run android --bundle --release --env.snapshot
tns run android --bundle
Works as expected:
tns run android --bundle --release --env.snapshot
tns run android --bundle

Don't clean the destination app folder when webpack process is already running

---

dependencyManager.js

Caused by: https://github.com/angular/devkit/pull/950

chore: downgrade webpack version to 4.6

---

CHANGELOG.md
package.json

Should be merged with `rebase and merge`.
We should add link to the migration blog post after it's published.

Changelog for 0.12.0

---

bundle-config-loader.js
register-modules.js

This is required, because there may be plugins that use the
tns-core-modules builder.
fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/561

fix: register UI modules in NG apps

---

package.json

When tns-creating an app that depends on latest nativescript-dev-webpack you can see the following in the output:
```
npm WARN schema-utils@0.4.3 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
```
Based on https://github.com/webpack-contrib/url-loader/issues/122 It seems schema-utils@0.4.5 has the webpack 4 dependency fix.

fix: schema-utils peer dep warning for webpack 2/3

---

bundle-config-loader.js
register-modules.js

Currently the regex for loading modules in non-angular apps is hardcoded and causes problems with apps that don't use the correct naming. 
Adds a `registerModules` option for the `bundle-config-loader` that allows users to specify custom regex to register their modules. Also if needed they can set the new option to `false` completely disabling automatic module registration for non-angular apps. 
Closes #556.

feat: add setting for plain modules regex

---

lib/before-watchPatterns.js
lib/compiler.js
lib/utils.js
plugins/WatchStateLoggerPlugin.ts
projectHelpers.js

Stop requiring the webpack config file in the hook, because that may have side effects. Instead tell the {N} CLI watcher to ignore the whole source dir.
fixes #584

fix: tell the {N} CLI to ignore the source dir when watching for changes

---

demo/AngularApp/package.json
dependencyManager.js

Revert to adding @ngtools/webpack instead of
@angular-devkit/build-angular because the later is ~150mb bigger and
slows down the {N} cloud builds.
Add @ngtools/webpack to the project dependencies only if
@angular-devkit/build-angular isn't there already. That's because the
@angular-devkit/build-angular already depends on @ngtools/webpack. This will prevent the
plugin from adding multiple instances of @ngtools/webpack to the project
which would cause the build to fail.
related to #571, #569
BREAKING CHANGES
Not really a breaking change but:
It's a good idea to remove the `@angular-devkit/build-angular` from the
package.json and add `@ngtools/webpack` instead as this will speed up
the build.
fixes #595

fix: add @ngtools/webpack to project deps only if @angular-devkit/build-angular is not a dependency

---

demo/AngularApp/package.json
dependencyManager.js

Temporarily reverting to @ngtools/webpack 6.1.0-rc.0 as we are not working correctly with latest rc1:
Related to https://github.com/NativeScript/nativescript-dev-webpack/issues/607

fix: webpack not working with latest @ngtools rc1

---

lib/compiler.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

related to https://github.com/NativeScript/nativescript-dev-webpack/issues/603

 feat: enable source maps when --env.sourceMap is provided

---

CONTRIBUTING.md
demo/AngularApp/package.json
demo/JavaScriptApp/package.json
demo/TypeScriptApp/.gitignore
demo/TypeScriptApp/app/app.android.css
demo/TypeScriptApp/app/app.ios.css
demo/TypeScriptApp/package.json

Updates:
- All demos - add `setup` script to refer `nativescript-dev-webpack` from a local `.tgz` file
- All demos - nativescript-dev-sass@next
- AngularApp - nativescript-angular@next
- TypeScriptApp - `.gitignore`

chore(demos): update dependencies

---

dependencyManager.js

We no longer need to hardcode @ngtools/webpack to 6.1.0-rc.0 as https://github.com/NativeScript/nativescript-dev-webpack/issues/607 is fixed with @ngtools/webpack 6.1.0-rc.2

chore: compiler cli & ngtools/webpack to latest rc

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

This will prevent webpack from adding a polyfill for `process` ([`process/browser.js`](https://github.com/defunctzombie/node-process/blob/master/browser.js)) whenever it sees this code: `typeof process`. What will change:
- process will be undefined instead of Object.
- `typeof process === 'undefined'` will return true
- Angular Animations won't assume the app is running in node context
([check](https://github.com/angular/angular/blob/d4ac9698ba7dd829600ca4c8129fcbeae9cb4bed/packages/animations/browser/src/render/shared.ts#L17)) and won't trigger logic which breaks {N} animations.
**Important**
This may break plugins that check if the `process` object is defined.
fixes https://github.com/NativeScript/nativescript-angular/issues/1433

fix: define process as undefined

---

templates/webpack.angular.js

The entryModule path can differ depending on what kind of project you're
using - mobile or web+mobile. While the best solution is to get the
mainPath from angular.json, not all {N} projects have that file. We'll
stick to the standard for web and web+mobile location - `appPath/main.ts`.
**Note** - We'll have to update {N} schematics to reflect this change.

refactor(angular): provide mainPath instead of entryModule to ng compiler plugin

---

templates/webpack.angular.js

It was removed (probably accidentally) in #634.

fix-next: add global process variable

---

lib/after-watch.js
lib/before-cleanApp.js
lib/before-preview-sync.js
lib/before-watch.js
lib/compiler.js
package.json
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js

`tns preview` command works without platform argument, so {N} CLI needs to start iOS webpack process when QR code is scanned with iOS device and android webpack process when QR code is scanned with Android device. Actually we need to have two separate webpack processes simultaneously. In order to do that we need to persist webpack process per platform.
When `tns preview --bundle` command is executed and QR code is scanned for example with Android device, {N} CLI starts a webpack process in watch mode for Android platform. If the webpack process for Android is already started, {N} CLI doesn't do anything. In order to archive the above things, a new hook is introduced - "before-preview-sync". This hook is used only from `tns preview` command.
When `tns run --bundle` command is executed, the …

feat: add hook for preview command

---

hot.js

If the update message is too long it gets trimmed.
Log each file separately to avoid that.

fix-next(hmr): HMR log is sometimes trimmed

---

lib/before-preview-sync.js

Add support for `tns preview --bundle --hmr`

fix: read the hmr option from the preview command

---

lib/before-watch.js

Webpack process does not stop when ctrl+c is pressed while executing tns preview --bundle command
Webpack process stops when ctrl+c is pressed while executing tns preview --bundle command
Rel to: https://github.com/NativeScript/nativescript-cli/pull/3897

chore:  stop webpack compiler when ctrl+c is pressed while executing `tns preview --bundle` command

---

templates/webpack.angular.js

The @ngtools/webpack should be applied to ngfactory and ngstyle files
and not only to TS files.
fixes #641

fix(angular): AoT rebuild on template and style changes

---

lib/before-watch.js

webpack process is not stopped when ctrl+c is pressed while executing `tns preview --bundle`
webpack process is stopped when ctrl+c is pressed while executing `tns preview --bundle`

fix: attach to process's exit event on correct place

---

lib/compiler.js

`startSyncFilesTimeout` is called twice with next versions of {N} CLI and `nativescript-dev-webpack` plugin
`startSyncFilesTimeout` is called only once with next versions of {N} CLI and `nativescript-dev-webpack` plugin

fix: don't call twice `startSyncFilesTimeout` method

---

hot.js
lib/compiler.js
lib/utils.js
plugins/WatchStateLoggerPlugin.ts

Currently there is no indication in the log, which hmr patch is applied and in hook args there is no data about the hmr hash and the files that should be synced if the hmr operation fails.
There is a hash added for start, success or fail of the hmr operation and there are properties in the `hookArgs` which are populated with information about current hmr operation.
Fixes/Implements/Closes [#3892](https://github.com/NativeScript/nativescript-cli/issues/3892).

feat: send data for fallback if hmr apply fails

---

lib/compiler.js

Hmr hash is not correct when more than one webpacks are started. So send hash per platform in order to ensure {N} CLI will receive the correct hash.
{N} CLI does not receive correct file's hash when 2 webpacks are started.
{N} CLI receives the correct file's hash when 2 webpacks are started.

fix: send hash per platform when more than one webpacks are stated

---

lib/after-watch.js
lib/before-watch.js
lib/utils.js

In case when the user runs 11 apps from sidekick (or only 2 apps changing them 6 times), 
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```
error is thrown. The problem occurs because we attach every time on `process.exit` and `liveSyncStopped` events. So this PR fixes this behavior as ensures only one listener is added for each event.
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```
error is thrown when the user runs 11 apps from sidekick (or only 2 apps changing them 6 times)
No error is thrown when the user runs 11 apps from sidekick (or only 2 apps changing them 6 times)

fix: don't throw MaxListenersExceeded error when more than 11 processes are started from sidekick

---

package.json

Due to security vulnerabilities in one of its dependencies
(`cryptiles`).

fix: update the version of `request`

---

package.json

Due to security vulnerabilities in one of its dependencies
(`cryptiles`).

fix: update the version of `request` (#694)

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

The next version of @ngtools/webpack is causing an `ERROR in Patterns must be a string or an array of strings` while a webpack build.
The webpack.configs are working with both the current and next versions of @ngtools/webpack.

fix: fix globs usage in CopyWebpackPlugin

---

bundle-config-loader.js
hot-loader-helper.js
markup-hot-loader.js
script-hot-loader.js
style-hot-loader.js

The context consists of an object with `type` and `module` properties:
- `type` could be `markup`, `script` or `style`
- `module` is the relative path to the module
Currently, `global.__hmrRefresh()` function accepts a`type` parameter which doesn't pass to `global.__onLiveSync` function.
The new behavior changes `global.__hmrRefresh()` function to accept a context `{ type, module }` object and pass it to `global.__onLiveSync` function.
In this way, the cross-platform modules (`tns-core-modules`) could handle different scenarios based on the context.
Relates to https://github.com/NativeScript/NativeScript/pull/6665.
Implements a part of https://github.com/NativeScript/NativeScript/issues/6645.

feat(HMR): expose context

---

.gitignore
jasmine-config/jasmine.json
package.json
projectHelpers.js
projectHelpers.spec.js

In case project's package.json uses tabs or multiple spaces for indentation, the postinstall script of nativescript-dev-webpack overwrites it with two spaces whenever it is executed.
The problem is that the plugin tries to modify the package.json and persists it on every operation.
Fix the behavior by checking the indentation character and use it when stringifying the content.
Also compare the current content of the file with the one we will write and skip the write operation in case they match.
Add unit tests for the new methods.
When the project's package.json is indented with tabs or more than two spaces, running the postinstall script of the plugin overwrites the content with indentation with two spaces.
Indentation is persisted. Also package.json will not be overwritten in case …

fix: project's package.json indentation is not persisted

---

dependencyManager.js
package.json

The plugin is not used in the webpack configurations anymore and can be removed.

refactor: remove unused `extract-text-webpack-plugin`

---

demo/TypeScriptApp/webpack.config.js
dependencyManager.js
package.json
templates/webpack.typescript.js

We executed some performance tests to compare `ts-loader` and `awesome-typescript-loader`. The difference in the build time between the two is insignificant. On the other hand, the `ts-loader` is 50% smaller than `awesome-typescript-loader` and is a dependency of the `nativescript-dev-webpack` package because it is needed in the {N}-Vue projects anyway.

feat(TypeScript): use `ts-loader` instead of `awesome-typescript-loader`

---

templates/webpack.vue.js

fix(Vue): resolve full path for entry module

---

lazy-ngmodule-hot-loader.js
projectHelpers.js
projectHelpers.spec.js
templates/webpack.angular.js

In NativeScript Angular the hot updates are only accepted in the entry file (`main.ts`). The lazy loaded NgModules are not directly imported anywhere in the dependency graph with root `main.ts`. That's why the hot updates in lazy modules don't bubble up to the accept in `main.ts` and HMR doesn't work in lazy modules.
Every lazy loaded NgModule is augmented with HMR self-accept during build by the `lazy-ngmodule-hot-loader`.
fixes https://github.com/NativeScript/nativescript-angular/issues/1564
BREAKING CHANGES:
The `lazy-ngmodule-hot-loader` should be added to the webpack configuration.
**BEFORE**
``` js
// webpack.config.js
{
test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
use: [
"nativescript-dev-webpack/moduleid-compat-loader",
"@ngtools/webpack",
]
},
// ...
```
**AFTER**
``` js
// …
```

fix(Angular): add hot loader for lazy loaded NgModules

---

templates/webpack.vue.js

When building {N} Vue apps in production mode the function names are renamed by UglifyJS to make the bundle smaller.
This causes problems when some `tns-core-modules` components are renamed (`SegmentedBar`, `FormattedString`).
```
tns run ios --bundle --env.production
```
The function names are not renamed anymore.
fixes https://github.com/nativescript-vue/vue-cli-template/issues/105 for the {N} CLI Vue template.

fix(Vue): disable mangling of function names when building in production mode

---

bundle-config-loader.js
demo/AngularApp/app/main.ts
demo/AngularApp/webpack.config.js
hmr/hmr-update.js
hot.js
templates/webpack.angular.js

Update demo and template.
Currently, a style change in `app.css` or `app.scss` is not accepted and causes application to restart.
The new behavior accepts changes in `app.css` or `app.scss` and uses the HMR context passed by `nativescript-dev-webpack` to determinate whether changes have been made to `app.css` or `app.scss`. If so, apply them at runtime and on back navigation.
Relates to https://github.com/NativeScript/NativeScript/pull/6665.
Implements the rest of https://github.com/NativeScript/NativeScript/issues/6645.

feat(Angular): apply changes in application styles at runtime with HMR

---

lazy-ngmodule-hot-loader.js

Currently, the `lazy-ngmodule-hot-loader` [adds](https://github.com/NativeScript/nativescript-dev-webpack/commit/6a9db32b9ef0205194d017f1803d2a5c6d21b4b8) a HMR self-accept to every lazy loaded NgModule during a build.
After [alignment](https://github.com/NativeScript/nativescript-dev-webpack/commit/fe4abfb548b91b12387c62ee6c168b1bd911214f) of the HMR lifecycle of NativeScript Angular with non-Angular applications, it requires a handler to update the app after module replacement.

fix-next(Angular): HMR for lazy loaded NgModules

---

bundle-config-loader.js
demo/AngularApp/app/main.ts
demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
hmr/hmr-update.js
hot.js
lazy-ngmodule-hot-loader.js

Print caught error's message on a `module.hot.check()` or a `module.hot.apply()` failure.
Also:
- expose a `latestHash` variable in the `hmr-update.js`,
- format properly the `HMR_HANDLER` snippet in bundles
- add module context parameter default value
- update module hot accept callback
Currently, if `module.hot.check()` or `module.hot.apply()` throws an error, the error's trace is printed.
Print error's message if truthy, if not - print error's trace.

refactor(HMR): print caught error's message

---

bundle-config-loader.js
demo/AngularApp/app/main.ts
hot-loader-helper.js
lazy-ngmodule-hot-loader.js

refactor(HMR): rename global.__hmrRefresh function

---

templates/webpack.vue.js

The `bundle-config-loader` executes for `entryPath` with all extensions: `css`, `js`, `ts`, `scss`, etc.
The `bundle-config-loader` executes only for `entryPath` with `js` or `ts` extensions.
Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/762.

fix(Vue): apply style changes with HMR

---

lazy-ngmodule-hot-loader.js

The `lazy-ngmodule-hot-loader` breaks sourceMaps as it does not pass them to the next loaders. This breaks debugging with `--bundle` in VSCode extension as the files included in the `sourcesContent` cannot be mapped correctly to local files.
* Unable to debug Angular projects in VSCode.
* When debugging Angular projects in Chrome DevTools, the content of the files under `webpack` is not the same as your actual content - it's not TypeScript anymore:
* You can debug Angular projects in VSCode
* Sources under webpack in Chrome DevTools are correct
Fixes issue NativeScript/nativescript-vscode-extension#232

fix: lazy-ngmodule-hot-loader breaks the sourceMaps

---

host/resolver.ts

The platform specific files resolver for `.tns`, `.ios`, `.android` files is having performance issues on webpack and seems to break (make it run very slow like its for the first time) the incremental compilation. This is happening in big projects with many files in the `node_modules` directory, as the current implementation makes a file system call for each file.
The resolver now handles only the files that are considered to support platform specific names e.g:
* packages in `node_modules` with `nativescript`, `tns` or `ns` anywhere in the name
* only files with following extensions: `[".ts", ".js", ".scss", ".less", ".css", ".html", ".xml", ".vue", ".json"]`

fix: optimize platform specific files resolver

---

markup-hot-loader.js
script-hot-loader.js
style-hot-loader.js

Use `this.rootContext` instead of `this.context`.
For example this [second-page](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/demo/TypeScriptApp/app/views/second-page.xml) module:
---> `this.resourcePath` is /Users/vchimev/git/nativescript-dev-webpack/demo/TypeScriptApp/app/views/second-page.xml
---> `this.context` is /Users/vchimev/git/nativescript-dev-webpack/demo/TypeScriptApp/app/views
---> `this.rootContext` is /Users/vchimev/git/nativescript-dev-webpack/demo/TypeScriptApp/app
---> `modulePath` should be ./views/second-page.xml
For example, this [second-page](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/demo/TypeScriptApp/app/views/second-page.xml) module resolves `modulePath` to `./second-page.xml`.
From the above example,`modulePath` …

fix-next(HMR): resolve correctly modulePath in hot loaders

---

index.js
index.spec.ts
package.json
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

In case `externals` are passed to webpack.config.js, they are converted to regular expression. The idea is to detect all imports for this module, for example if it is `nativescript-vue`, we would like to make externals imports like `nativescript-vue/somesubdir/file1`.
However, the regular expression we construct also matches packages like `nativescript-vue-template`.
Fix the regular expressions in all template webpack.config.js files and add unit tests for them.
Add devDependency to `proxyquire` as the webpack configs that are tested, require some packages that are not available in node_modules of `nativescript-dev-webpack` (including the `nativescript-dev-webpack` itself). This is expected for the `webpack.config.js` files, as they should be placed in the NativeScript applications, so …

fix: some packages are treated as externals when they shouldn't

---

templates/webpack.angular.js
templates/webpack.config.spec.ts
transformers/ns-replace-bootstrap.spec.ts
transformers/ns-replace-bootstrap.ts
transformers/ns-replace-lazy-loader.ts
transformers/ns-support-hmr-ng.spec.ts
transformers/ns-support-hmr-ng.ts
utils/ast-utils.ts

Related to https://github.com/NativeScript/nativescript-cli/issues/4325

feat: support HMR in Angular apps

---

transformers/ns-support-hmr-ng.spec.ts
transformers/ns-support-hmr-ng.ts

A runtime exception is thrown when you bootstrap your Angular app using a variable as App options like:
`const appOptions = { bootInExistingPage: true };
platformNativeScriptDynamic(appOptions).bootstrapModule(AppModule);`
The case is properly handled and covered by an unit test.

chore(ns-support-hmr-ng transformer): support app options variable

---

templates/webpack.angular.js
utils/ast-utils.ts

fix: add a typescript module resolution when searching for the main Angular module location

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

The iOS Runtime calls it explicitly by name and it has to be emitted
in `tns_modules/tns_core_modules`
Refs: https://github.com/NativeScript/ios-runtime/issues/1054, https://github.com/NativeScript/ios-runtime/issues/1055
https://github.com/NativeScript/ios-runtime/issues/1056, https://github.com/NativeScript/ios-runtime/issues/1057

fix: Emit inspector_modules.js as a separate entry point for iOS

---

host/resolver.ts

Only explicit modules to resolve can be configured.
The node_modules packages filter and the platform specific files extension list can also be configured.

feat: allow angular resolver configuration via webpack.config

---

lib/utils.js
markup-hot-loader.js
script-hot-loader.js
style-hot-loader.js

Replace backslashes with forward slashes.
Fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/806.

fix(HMR): modulePath on Windows to apply changes in app styles at runtime

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Currently every start of the compilation will generate the same compilation hash for the same content. This hash is also used to chain Hot Module Reloads.
To reproduce: 
1 Generate a HMR patch which breaks the app, then kill the compiler. 
2 Revert the change and restart the compiler the application remains broken. 
This is happening, because the hash of the second compilation is the same as the initial and it decides to apply the patch causing the error.
Every initial compiler run creates unique compilation hash.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-cli/issues/4123

fix: initial compilation always generates same compilation hash

---

templates/webpack.vue.js

The JS and Angular templates include an option to enable sourcemaps, the Vue one doesn't. This means the VS Code integration (or any debugger) cannot breakpoint and debug as sourcemaps are not present.
The Vue template has an option for enabling sourcemaps, using `--env.sourceMap`
I've tested this by debugging with breakpoints VS Code, which is fixed by this change.
[CLA]: http://www.nativescript.org/cla ✅

feat(Vue): option to enable sourcemaps

---

lib/compiler.js

`Cannot read property 'kill' of undefined` error is thrown when `ctrl+c` is pressed immediately after webpack process is started and still is not persisted
`Cannot read property 'kill' of undefined` error is thrown when `ctrl+c` is pressed immediately after webpack process is started and still is not persisted

fix: fix "Cannot read property 'kill' of undefined" error

---

templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

The assets from the `App_Resources/${platform}` folder are copied to the out directory (`platforms/.../app`) by the `CopyWebpackPlugin`. This step is not required when running `tns preview`, because no native build is performed and the native resources are not needed.

refactor: skip copying of the native app resources on `tns preview`

---

lib/after-watch.js
lib/before-watch.js
lib/compiler.js

Currently the message `Stopping webpack watch` is printed whenever CLI executes `after-watch` hooks, i.e. when user runs `tns run <platform>` and sends Ctrl+C, the message is shown. However, we have not started any webpack process, so there's nothing to stop.
Print the message only when webpack process had been started. Also print it only when `--log trace` is used.
Message `Stopping webpack watch`  is shown when you execute `tns run <platform>` (without `--bundle`) and press `Ctrl + C`.
Message `Stopping webpack watch`  is shown only when you execute `tns run <platform> --bundle` and press `Ctrl + C`.

fix: show message for stopping webpack only when it has been started

---

transformers/ns-replace-bootstrap.spec.ts
transformers/ns-replace-bootstrap.ts

The changes are based on the ones in the Angular CLI - https://github.com/angular/angular-cli/commit/7347d881925130ce325009588b20d5b39ac73258#diff-6b9947d457bac2310a5d25e102697423R85
The AOT transformer is always changing the bootstrap call to `bootstrapModuleFactory` which is not valid for Ivy compatible modules.
The transformer is using `bootstrapModule` or `bootstrapModuleFactory` based on the `enableIvy` flag.
Connected to https://github.com/NativeScript/nativescript-dev-webpack/issues/827

feat: Support Angular Ivy modules with AOT

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Currently bundle-config-loader is executed for any file of the application with the same name as main entry file. For example if the javascript application has app.js file located in `./app/some-folder/app.js`, the bundle-config-loader will be executed for this file.
`bundle-config-loader` is executed for any file of the application with the same name as main entry file
`bundle-config-loader` is executed only for the entry point of the application

fix: execute bundle-config-loader only for the entry point of the application

---

bundle-config-loader.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js
unit-testing-config-loader.js

https://github.com/NativeScript/nativescript-cli/issues/4392
`tns test --bundle` command does not work
`tns test --bundle` command works
https://github.com/NativeScript/nativescript-cli/issues/4392

feat: Implement unit testing with bundle

---

index.js
index.spec.ts
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

In a previous commit we've changed the check when to execute the `bundle-config-loader` to be based on full path. However, the created RegExp does not match anything on Windows as the paths contain `\`, which are used for escape symbol inside RegExp.
Escape the `\` and update all webpack configs with the new RegExp.
Application built with Webpack on Windows fail at runtime.
You can build applications with Webpack on all OSes.

chore: entryPath check should work on Windows

---

plugins/WatchStateLoggerPlugin.ts

Take a look at the issue.
The app will crash when you delete a required file or throw an error in the code.
related to: https://github.com/NativeScript/nativescript-cli/issues/4441

fix: stop deleting chunks with compilation errors

---

index.js
package.json
plugins/NativeScriptAngularCompilerPlugin.ts
plugins/index.js
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

If you make your entry point (main.ts) a platform-specific file (main.ios.ts and main.android.ts), the webpack compilation will fail. The compilation also fails when the entry point of a linked plugin is a platform-specific file (take a look at the related issue).
The platform-specific files are supported entry points of your app and the linked plugins.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/612

fix: support platform specific files that are not directly imported anywhere in the app

---

plugins/NativeScriptAngularCompilerPlugin.ts

In case you change `.html` file in Angular application, during `tns run <platform> --bundle`, the application will be restarted and an error will be shown.
This happens as in some cases, the `getCompiledFile` method from Angular compiler does not throw an error when it is unable to find a file, but instead it returns an object with empty outputText and array of errors (errorDependencies).
Fix the liveSync in these cases by checking the result of the Angular compiler and fallback to non-platform specific file in the mentioned case.
Unable to use LiveSync in Angular applications.
LiveSync works in Angular applications.

chore: fix liveSync of html files in Angular apps

---

demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
package.json
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

We were using an old version of the css loader containing the following issue: https://github.com/webpack-contrib/css-loader/issues/578 and causing the below-mentioned issue in NativeScript apps.
The below-mentioned issue is fixed in the latest version of the css-loader.
Related to: #846

fix: update the css loader in order to fix a bug with leading dashes in css classes

---

unit-testing-config-loader.js

Rel to:
https://github.com/NativeScript/nativescript-cli/issues/4477
https://github.com/NativeScript/nativescript-cli/issues/1798

fix: respect ts files on `test` command

---

CHANGELOG.md
unit-testing-config-loader.js

chore: merge release into master

---

unit-testing-config-loader.js

fix: use correct slashes on windows on test command

---

index.js
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

The `hidden-source-map` is the same as `source-map`, but it doesn't add a reference comment to the bundle. It is meant to be used when you only want SourceMaps to map error stack traces from error reports from tools like crashlytics, but you don't want to expose your SourceMap for the development tools in the release builds.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/817

feat: support hidden source maps to map error stack traces from crash reports

---

templates/webpack.angular.js

The "ERROR in Must have a source file to refactor." error is thrown when `tns test android --path <projectPath> --bundle` command is executed. 
This error is thrown from `AngularCompilerPlugin` when the path to `main.ts` file is not correct. We provided the path to `main.ts` file [here](https://github.com/NativeScript/nativescript-dev-webpack/blob/dbcfbc2eb97f3907405b1a384e5086f4d6ed8522/templates/webpack.angular.js#L93). As this path is built using `path.resolve` and `appPath` is [relative path](https://github.com/NativeScript/nativescript-dev-webpack/blob/dbcfbc2eb97f3907405b1a384e5086f4d6ed8522/templates/webpack.angular.js#L41), the resulting path is still not an absolute path. In this case NodeJS uses current working directory as described …

fix: fix "ERROR in Must have a source file to refactor." error from ngCompilerPlugin on `test` command

---

android-app-components-loader.js
apply-css-loader.js
bundle-config-loader.js
css2json-loader.js
markup-hot-loader.js
script-hot-loader.js
style-hot-loader.js
templates/webpack.typescript.js
xml-namespace-loader.js

fix: typescript source maps are containing javascript code

---

lib/compiler.js
lib/utils.js
plugins/WatchStateLoggerPlugin.ts

Take a look at the related issue.
We are skipping the Webpack runtime chunks when sending files for the HMR updates.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/868

fix: ignore the Webpack runtime chunks when sending HMR updates

---

package.json
templates/webpack.typescript.js

See #877
`ts-loader` running in `transpileOnly` mode with HMR (as [suggested in docs](https://github.com/TypeStrong/ts-loader#hot-module-replacement)). Type-checking assured with [`fork-ts-checker-webpack-plugin`](https://github.com/Realytics/fork-ts-checker-webpack-plugin) (also as suggested in the [`ts-loader` docs](https://github.com/TypeStrong/ts-loader#transpileonly-boolean-defaultfalse))

fix(hmr): run ts-loader in transpileOnly mode

---

package.json

**Problem**: `fork-ts-checker-webpack-plugin@1.3.1` has a `dependency` to `@types/webpack` which has a `dependency` to `@types/node`.
Because these are direct dependencies you get `@types/node` installed in your NS project which causes problems - clashing node types in NS project.
**Solution**: Freeze the version `freeze fork-ts-checker-webpack-plugin` to `1.3.0` which does not have the  `@types/webpack` dependency.

chore: freeze fork-ts-checker-webpack-plugin

---

snapshot/android/snapshot-generator.js
snapshot/android/utils.js

When the download of the snapshot tools fails, the corrupted executables are not cleared and any consecutive build will fail instead of trying to download the again.
If the download fails we remove the corrupted/partial files and the next build will try to download the again.
Fixes/Implements/Closes  https://github.com/NativeScript/nativescript-dev-webpack/issues/591

fix: clean up snpashot tool on download fail

---

CHANGELOG.md

release: cut the 0.22.0 release

---

dependencyManager.js
package.json
projectHelpers.js
templates/webpack.angular.js
transformers/ns-replace-bootstrap.spec.ts
transformers/ns-replace-bootstrap.ts
transformers/ns-replace-lazy-loader.spec.ts
transformers/ns-replace-lazy-loader.ts
transformers/ns-support-hmr-ng.spec.ts
utils/transformers-utils.ts

A `workaroundResolve is not a function` error is thrown with Angular 8 (@ngtools/webpack@8.0.0)
The Angular apps are properly built with Angular 8.
Related to: https://github.com/NativeScript/nativescript-angular/issues/1833 https://github.com/NativeScript/nativescript-angular/pull/1831

fix: import the workaroundResolve funciton based on the Angular version (it was moved from compiler_host to utils in Angular 8)

---

demo/AngularApp/package.json
demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
dependencyManager.js
plugins/GenerateBundleStarterPlugin.js
plugins/GenerateNativeScriptEntryPointsPlugin.js
plugins/NativeScriptSnapshotPlugin/index.js
plugins/index.js
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/900 and https://github.com/NativeScript/nativescript-dev-webpack/issues/699

fix: unify the entry points handling and enable custom applications support in android

---

plugins/GenerateNativeScriptEntryPointsPlugin.js
plugins/NativeScriptSnapshotPlugin/index.js

When a custom filename is set in the Webpack output property (e.g. output.file…name: "[name].custom.js"), the plugin is throwing an exception.
The custom filenames are properly handled.

fix: handle entry points with custom output filename

---

templates/webpack.typescript.js
templates/webpack.vue.js

In case `declaration` is set to true in `tsconfig.json` file, the webpack watcher goes in indefinite loop as each change of .ts file leads to generation of new .d.ts files which are also detected by webpack.
To prevent this, ensure declaration is set to false in all compilation cases.
Check related issue.
Transpilation is working correctly.
Fixes issue https://github.com/NativeScript/nativescript-dev-webpack/issues/823

fix: stop generating .d.ts on TS compilation

---

plugins/GenerateNativeScriptEntryPointsPlugin.js

They have to be required and processed by the Webpack runtime.

fix: do not include hot updates when generating requires in entry files

---

templates/webpack.typescript.js

Take a look at the related issue.
The types check is always incremental and handled in a child process.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/925

fix: handle types check in a child process

---

plugins/GenerateNativeScriptEntryPointsPlugin.js

Fixes tns_modules/tns_core_modules/inspector_modules

fix: handle file dependencies in non root entry modules

---

demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

This entry point does not resolve when transpiling `tns-core-modules`.
`inspector_modules.js` *file* is emitted as a separate entry point for iOS.
`inspector_modules` *module* is emitted as a separate entry point for iOS.

fix(ios): emit inspector_modules as a module

---

templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Related to: https://github.com/NativeScript/nativescript-cli/issues/4658

fix: do not add inspector_modules entry when core modules are an external module

---

templates/webpack.javascript.js

We are already following the symlinks in TypeScript, Angular and Vue apps. It allows the plugin developers to link and develop their plugins directly in a JavaScript demo application
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/656

fix: follow the symlinks in JavaScript apps

---

demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
plugins/PlatformFSPlugin.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Currently `hmr` for platform specific files in linked plugins work only in intervals of 60 seconds. This is due to the fact that `CachedInputFileSystem` of `webpack` has a cache that is invalidated on every 60seconds. We used `ExtaWatchPlugin` in order to add platform specific files to the webpack's compilation. This plugin doesn't follow symlinks and this led to the different problems when applying changes from platform specific files. So we decided to remove it and to override correctly watch's file system from webpack. We have a logic for overriding webpack's watchFileSystem but this logic doesn't work as it seems it is not compatible with webpack v4.0.
Currently `compiler.watchFileSystem.watch` has 2 callbacks - `callback` and `callbackUndelayed`. The `callbackUndelayed` is executed …

fix: fix hmr for platform specific files in linked plugins

---

projectFilesManager.js

When you add a new line at the end of your `webpack.config` or `tsconfig.tns.json`, the postinstall will show a warning that your configs are outdated.
The whitespace changes are ignored during the comparison.

fix: do not show warning for format differences in templates

---

lib/after-prepare.js

Rel to: https://github.com/NativeScript/nativescript-dev-webpack/issues/945

fix: don't throw an error from after-prepare hook when running legacy workflow with CLI <= v5.4.2 and nativescript-dev-webpack@next

---

unit-testing-config-loader.js

Currently the app.css file from unit-test-runner is not included in bundle/vendor files on test command so the application remains without app.css file.  The `tns-core-modules` shows an error in this situation in their latest next versions:
```
JS: Error: Could not load CSS from ./app.css: Error: com.tns.NativeScriptException: Failed to find module: "./app.css", relative to: app//
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1212)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1092)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1079)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1059)
JS: …
```

fix: inject app.css file from unit-test-runner on test command

---

plugins/WatchStateLoggerPlugin.ts

Currently `hmr` with `--env.uglify` is not working as the uglifier touches all files. This leads to emit of files that are not hot updates. When CLI finds such files, it decides hmr is not successful and restarts the application.
However, some of the emitted files are not actully changed. These emitted (and not changed) files are chunks of the entry points - as we are with HMR if there's an actual change for them, we'll receive hot-update files.
Currently there's a logic to skip all emitted entry points and webpack runtime files (`runtime.js`) when we are with HMR. To fix the current issue, extend this logic to skip emitted chunks of entry points as well  when we are with HMR and there's no hot-update for them.
[CLA]: …

fix: hmr should work with uglify

---

demo/AngularApp/app/activity.android.ts
demo/AngularApp/app/main.ts
demo/AngularApp/webpack.config.js
demo/JavaScriptApp/app/activity.android.js
demo/JavaScriptApp/app/app-root.xml
demo/JavaScriptApp/app/app.js
demo/TypeScriptApp/app/activity.android.ts
demo/TypeScriptApp/app/app-root.xml
demo/TypeScriptApp/app/app.ts

refactor: fix deprecated APIs

---

unit-testing-config-loader.js

Currently `tns test` command on windows throws the following error:
```
ERROR in ./app.js
Module not found: Error: Can't resolve '..
ode_modules
ativescript-unit-test-runnerapp.css' in 'C:\Jenkins\workspace\master-cli-test-windows\TestApp\app'
@ ./app.js 12:93-157
Webpack compilation complete.
{ Error: Executing webpack failed with exit code 2.
at DevicesService.<anonymous> (C:\Jenkins\workspace\master-cli-test-windows\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:368:38)
at Generator.throw (<anonymous>)
at rejected (C:\Jenkins\workspace\master-cli-test-windows\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:11:65)
at process._tickCallback (internal/process/next_tick.js:68:7)
allErrors:
[ { Error: Executing webpack failed with exit …
```

fix: fix app.css file path on windows machines

---

lib/before-checkForChanges.js
package.json
postinstall.js
preuninstall.js

During migration from one version to another or when the plugin is removed from application we need to remove its hooks. This is usually done in preuninstall script, however, it was missing until now. This causes several issues when the version is updated as old hooks remain, but they may not be valid anymore.
As in 1.0.0 and CLI 6.0 we've changed the way nativescript-dev-webpack interacts with CLI, we need to remove hooks from previous nativescript-dev-webpack versions and use new ones. Usually this should happen with preuninstall script of the old version that removes the hooks. However, our current live version does not have such logic, so implement this in the postinstall of the current version.
This way we try to ensure the current plugin will work correctly.
feat(hooks): add …

feat(hooks): improve hooks handling

---

plugins/WatchStateLoggerPlugin.ts

Currently there is a logic that gets all runtime files and entry point files from webpack compilation. These files are needed to CLI in order to decides if the application should be restarted or refreshed on device(when there is at least one file that is not hot update file, CLI restarts the application). However, this logic doesn't work for lazy loaded modules in angular application as they are reported neither entry point files nor runtime files. Lazy loaded modules are directly injected into webpack compilation using the hooks of ContextModuleFactory - https://github.com/angular/ngtools-webpack-builds/blob/39ccb0b487e92a7ac4330ff9db821337b7aa5c45/src/angular_compiler_plugin.js#L516.  This PR fixes the behavior with lazy loaded files as it gets all chunks produced from webpack …

fix: don't restart application when lazy loaded code is changed in angular app with uglify option

---

demo/TypeScriptApp/package.json
transformers/ns-replace-lazy-loader.spec.ts
transformers/ns-replace-lazy-loader.ts

Create PropertyAssignment instead of string literal (Identifier) when modifying the NgModule.
It seems that in some cases (e.g. when there is decomposition in another NgModule property), the TypeScipt program is trying to read `node.name.kind` for each property causing an exception for Identifiers)
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/960

fix: the Lazy transformer is not crashing the TypeScript program anymore

---

templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

By default `global.process` will be `undefined` but the plugins and the app developers will be able to polyfill it. This will unify the behavior with the Legacy Workflow.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/921

fix: allow overriding the `global.process` object

---

package.json

Update `webpack-bundle-analyzer` dependency to `3.3.2` to address vulnerability [WS-2019-0058](https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/263)

build(package): Update webpack-bundle-analyzer

---

demo/TypeScriptApp/package.json
lib/before-checkForChanges.js
package.json
plugins/WatchStateLoggerPlugin.ts
postinstall.js
preuninstall.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js
transformers/ns-replace-lazy-loader.spec.ts
transformers/ns-replace-lazy-loader.ts

chore: merge release in master

---

snapshot/android/snapshot-generator.js

Bonus: the snapshot tool is now logging the real JS error.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/920

fix: avoid generating invalid JavaScript when merging IIFE files

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
bundle-config-loader.js
bundle-config-loader.ts
demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
hmr/hmr-update.js
hmr/hmr-update.ts
hmr/hot-loader.ts
hmr/index.js
hmr/index.ts
jasmine-config/jasmine.json
package.json
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

In this PR:
- Bundle config loader will add all `.xml`/`.js/ts`/`.css` files to the bundle (except files in the `App_Resources`). Previously it was only files with `-page` suffix.
- Added `hmr/hot-loader` which is used for JS and TS templates. It will process all `.xml`/`.js/ts`/`.css` files and it will add code that will enable HMR self-accept (`module.hot.accept()`) if the module was loaded from `tns-core-module/ui/builder` using the `global._isModuleLoadedForUI()` API from this PR: https://github.com/NativeScript/NativeScript/pull/7462
- bundle-config-loader and modules in `hmr/` folder converted to TypeScript
**Warning**: This PR should be merged together with his brother -> https://github.com/NativeScript/NativeScript/pull/7462
If you have custom android application or activity it is …

refactor: HMR and webpack improvements

---

bundle-config-loader.ts
demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
index.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

fix: handle the `bundle-config-loader` require.context change without breaking changes for the end-users

---

bundle-config-loader.ts

Newly created or deleted files cause changes in `./ sync recursive ( ....)$` module (created by the `require.context` added bu bundle-config-loader). These changes cause app restart as they are not handled by HMR.
Added `hot.accept()` for the  `./ sync recursive ( ....)$` module just after it is added in the app-entry point (`app.ts/js`). This will accept hot-updates for it when files are added/deleted/renamed.
**Note**: If the modified files are required somewhere in the app they will still be handled by the regular HMR handling.

fix: auto accept new or deleted files

---

unit-testing-config-loader.js

Rel to: https://github.com/NativeScript/nativescript-unit-test-runner/pull/41

fix: require automatically only files from app folder of unit-test-runner

---

unit-testing-config-loader.js

With the latest rc of nativescript-dev-webpack it is not possible to run unit tests as the nativescript-dev-webpack searches for app folder inside runner root folder. As such folder doesn't exist in live version of nativescript-unit-test-runner, test command throws an error.

fix: fix the execution of unit tests with latest unit-test-runner and nativescript-dev-webpack@rc

---

.vscode/launch.json
bundle-config-loader.spec.ts
bundle-config-loader.ts
package.json

Partial `.scss` are included in the bundle by `BundleConfigLoader`.
Partial `.scss` are **not** included in the bundle by `BundleConfigLoader`.

fix: don't include partial scss files in bundle

---

dependencyManager.js

The following helper message is displayed after installation of the
plugin:
```
NativeScript Webpack plugin was successfully added.
You can now bundle your project by passing --bundle flag to NativeScript CLI commands:
- tns build android --bundle
- tns build ios --bundle
- tns run android --bundle
- tns run ios --bundle
You can also pass the "--env.uglify" flag to use UglifyJS for minification.
For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.
```
With {N} 6.0, this message is not relevant any more:
1). the `bundle` flag is not needed for webpack builds;
2). the default build/run workflow uses webpack.

refactor: remove the postinstall helper info

---

index.js
index.spec.ts

Currently `bundle-config-loader` is not loaded when there is a special symbol in app's path. 
Rel to: https://github.com/NativeScript/nativescript-cli/issues/4844 

fix: escape the regex for the path to the entry module of application

---

demo/AngularApp/webpack.config.js
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js
index.js
index.spec.ts
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Currently the app crashes as the entry module is not resolved.
The app is working as expected and there are no escaping RegEx reserved symbols from path.
Rel to: https://github.com/NativeScript/nativescript-dev-webpack/issues/998

fix: vue template crashes on start

---

projectFilesManager.js
projectHelpers.js

The NativeScript Angular code-sharing projects, built with the
[recommended structure](https://docs.nativescript.org/angular/code-sharing/intro), have a different `tsconfig.tns.json` file
compared to the rest of the {N} project flavors. The update script,
distributed by the `nativescript-dev-webpack` plugin shouldn't override
that file when executed in a code-sharing project.

fix(update-ns-webpack): skip the update of tsconfig.tns.json in shared Angular projects

---

plugins/GenerateNativeScriptEntryPointsPlugin.js

Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/989#issuecomment-514253061

fix: avoid getting invalid require calls when building from Windows

---

package.json
plugins/GenerateNativeScriptEntryPointsPlugin.js

Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/968#issuecomment-514581546

fix: require dependencies only in sourceFiles (avoid getting invalid `.js.map` files)

---

load-application-css-angular.js

Since https://github.com/NativeScript/NativeScript/pull/7631 the `tns-core-modules` now looks for `app.css` package to load (instead of `./app.css`) for loading the global css file.
BREAKING CHANGES:
This might be a breaking change for folks using custom `app.css` file using approach described in  https://github.com/NativeScript/nativescript-dev-webpack/issues/587. The fix would be to do `global.registerModule("app.css", () => require("~/app1.css"));`

fix: register non-relative app.css module

---

hmr/hmr-update.ts
hot.js

Currently the check for hot update creates a new file in case it does not exist (as the method from tns-core-modules is doing this). This is a problem when trying to install `.ipa` on device and the `.ipa` file contains JavaScript files with HMR enabled.
This may happen in case you run `tns run ios` on device and after command finishes the execution open the project in Xcode and deploy the app from there or uninstall it from device and install the produced `.ipa` manually. The problem in the mentioned scenarios is that the JavaScript file cannot write files in the directory where the `.ipa` is installed.
When `tns run ios` is executed, it livesyncs the files in a different location, so the HMR can create the files there.
To fix the issue check if the hmr file exist before reading its …

fix(hmr): check for hot update should not create new file

---

package.json
plugins/NativeScriptSnapshotPlugin/options.json
snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js

Add ia64 as supported architecture and map it to x86_64 Android arch.
NOTE: use ia64 only if runtime is 6.0.2 or later  …
Older runtimes cannot work with ia64 arch (they do not have the x86_64 arch), so check the runtime version and remove the ia64 (and all new archs that we may add in the future).
You cannot use snapshot for building ia64 version (x86_64).
In case Android runtime version is 6.0.2 or later, ia64 (x86_64) snapshot will be automatically built.
Related to https://github.com/NativeScript/nativescript-dev-webpack/issues/1030 and NativeScript/nativescript-cli#4330

fix: add ia64 as supported architecture

---

plugins/NativeScriptSnapshotPlugin/options.json

When the runtime version is below 6.0.2 we should generate snapshot only for armv7, arm64 and ia32 archs. However, as in the validation schema we have default value for the targetArchs, the logic that should determine if ia64 should be removed from the targetArchs decides the archs are passed by the user and does not strip anything from them. Remove the default values from the JSON Schema - they are calculated in the code, so there's no need to have them on two places. As we can not have our conditional logic in the JSON schema, keep calculation of the default values only in the code.
When Runtime 6.0.1 is used, snapshots are generated for 4 architectures. The ia64 is invalid.
When Runtime 6.0.1 is used, snapshots are generated for 3 architectures. 
Fixes/Implements/Closes #[Issue …

fix: stop generating snapshot for ia64 for older runtimes

---

demo/AngularApp/tsconfig.tns.json
demo/TypeScriptApp/tsconfig.tns.json
templates/tsconfig.tns.json

Currently, the following syntax is not supported in TS projects
```
import(`~/app/home/home.module`)
```
The dynamic import will be supported in TS/Angular projects.
See also: https://github.com/NativeScript/nativescript-app-templates/pull/68

feat: support dynamic ES6 import

---

CHANGELOG.md

chore: add changelog for 1.2.0 release

---

package.json

Currently `extra-watch-webpack-plugin` is not used anymore and should be deleted from package.json.
`escape-string-regexp` is required from [bundle-config-loader](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/bundle-config-loader.ts#L4) but it is not dependency of `nativescript-dev-webpack` plugin. It's working at the moment because it is dependency of [fork-ts-checker-webpack-plugin](https://github.com/NativeScript/nativescript-dev-webpack/blob/2978b81b5a8100774b2bb4a331ac8637205927b8/package.json#L54).

fix: fix dependencies in package.json

---

.gitignore
.npmignore
.nycrc
jasmine-config/jasmine.json
package.json
templates/webpack.config.spec.ts

Only tests in the root of the repo were executed with `npm test`
- All tests (including nested folders) are executed with `npm tests`
- Added `npm run coverage` that will report code-coverage using `nyc` (a.k.a. "the new istanbuljs")

chore: Enable all unit test and test coverage

---

plugins/NativeScriptSnapshotPlugin/index.js
plugins/NativeScriptSnapshotPlugin/options.json
snapshot/android/project-snapshot-generator-cli-ags-parser.js
snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js
snapshot/android/utils.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

We are not able to build snapshots on macOS Catalina.
We are able to build snapshots on macOS Catalina using a Docker container.
Docker Image repository: https://github.com/NativeScript/docker-images/tree/master/
Related to: #1038

feat: support snapshots in Docker

---

snapshot/android/snapshot-generator.js

Fixed a wrong path from the previous PR. The `xxd` tool is globally available on macOS and Linux. The `/bin/` location is available only in the Docker image.

fix-patch: fix xxd path for local snapshots generation

---

plugins/WatchStateLoggerPlugin.ts
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js
utils/ast-utils.ts
utils/tsconfig-utils.ts

Webpack doesn't notify NativeScript CLI when there is a compilation error. So, NativeScript CLI build the app, install it on device and start it. In most cases the application crashes runtime as the webpack compilcation is not successful. Most probably there would be a red/yellow message in the console printed during the compilation. The users don't see the error message as there is too much log outputed in the console. They don't understand the exact reason why their app crashes runtime.
Webpack has a mechanism to skip the emitting phase whenever there are errors while compiling. This can be achieved using `optimization.noEmitOnErrors` property as it is described [here](https://webpack.js.org/configuration/optimization/#optimizationnoemitonerrors). This PR adds `noEmitOnErrors` property …

fix: handle correctly webpack compilation errorrs

---

lib/before-checkForChanges.js
lib/utils.js
snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js

Providing the `--env.snapshot` flag on Windows is throwing an exception.
The `--env.snapshot` flag is valid on Windows and it is generating snapshots in a docker container.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/1054 and https://github.com/NativeScript/nativescript-cli/pull/5037

feat: support V8 snapshots on Windows

---

xml-namespace-loader.spec.ts
xml-namespace-loader.ts

`xml-namespace-loader` throws error when encounters `&` in attribute value.
`xml-namespace-loader` will only emit warning in this case. Having `&&` in an attribute value might happen if you have a binding expression.

refactor: emit warning for invalid & in XML

---

bundle-config-loader.spec.ts
bundle-config-loader.ts

Currently unit tests files and their dependencies are always included in the built application regardless if `tns test` or another command is executed. This way the size of built package is increased as all unit test related dependencies are included (such as mocha, chai, angularTestBed and their dependencies as well).
Rel to https://github.com/NativeScript/nativescript-dev-webpack/issues/1041

fix: exclude files from tests folder from built application

---

host/resolver.ts

Nativescript host resolver (used in angular projects) does not recognize package in `@nativescript` scope as "nativescript" packages and so does not resolve platform-specific files in there.
`"@nativescript"` added in host resolver's list of nativescript packages.

feat: support @nativescript scope in host  resover

---

androidProjectHelpers.js
lib/utils.js
package.json
snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

Related to: https://github.com/NativeScript/nativescript-cli/issues/5049 https://github.com/NativeScript/android-runtime/pull/1498/files https://github.com/NativeScript/android-runtime/pull/1496/files

feat: support useLibs though env.compileSnapshot and calculate the NDK path internally

---

snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js

Related to: https://github.com/NativeScript/nativescript-cli/issues/5049

refactor: improve android NDK logging

---

snapshot/android/snapshot-generator.js
snapshot/android/utils.js

Related to: https://github.com/NativeScript/nativescript-cli/issues/5089

fix: search for the proper NDK executable on Windows

---

package.json

We have a limitation that webpack compilation doesn't stop on error in typescript applications. That was due to the issue in `fork-ts-checker-webpack-plugin`. After merging [the PR that fixes the issue](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/337) and releasing 2.0.0 version of the plugin, we can update it on our side and that way webpack compilation will stop on syntax/semantic errors within the application.
Rel to: https://github.com/NativeScript/nativescript-cli/issues/3785

fix: stop on compilation error in typescript applications

---

bundle-config-loader.ts

The initial app start is not calling the core modules' `__onLiveSync` method as it expects that the changes are already applied. However, the HMR updates and the app start are asynchronous and when the app starts before the Hot Updates, the core modules are never updated. 
We always call the core modules' `__onLiveSync`  in order to ensure that the hot updates will affect the app state.
Related to: https://github.com/NativeScript/worker-loader/issues/41 https://github.com/NativeScript/nativescript-dev-webpack/issues/1082

fix: stop ignoring the initial hot updates

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add phrases in pull request template

---

index.js
templates/webpack.angular.js
templates/webpack.config.spec.ts
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js

It's not possible to use the plugin without the `tns-core-modules` proxy package because we inject `tns-core-modules` require statements in the app.
The plugin injects the require statements based on the `@nativescript/core` package availability.
1) The code is meant to be backward compatible (it should work with core modules before 6.2.0.)
2) The "short imports" syntax is also supported in the "scoped packages only" flow.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/1089

feat: stop using the proxy `tns-core-modules` package when the `@nativescript/core` is available

---

demo/AngularApp/webpack.config.js
demo/JavaScriptApp/app/app.android.css
demo/JavaScriptApp/app/app.ios.css
demo/JavaScriptApp/webpack.config.js
demo/TypeScriptApp/webpack.config.js

As the demo applications are with outdated webpack.config files, we should update them to the latest webpack.config

chore: update demo applications

---

plugins/GenerateNativeScriptEntryPointsPlugin.js

Fixes/Implements/Closes https://github.com/NativeScript/nativescript-dev-webpack/issues/1096

fix: bundle emitted on save without changes

---

css2json-loader.spec.ts
css2json-loader.ts

There is an issue when importing local css file as module as the `css2json-loader` handles it as a module instead of a local file. So, the webpack throws an error that it is not able to find the module. This PR fixes this issue as changing the method used to get the correct file uri with the method used by `css-loader` itself - https://github.com/webpack-contrib/css-loader/blob/967fb66da2545f04055eb0900a69f86e484dd842/src/utils.js#L220.
Rel to: https://github.com/NativeScript/nativescript-dev-webpack/issues/1098

fix: fix module import of local css files

---

snapshot/android/project-snapshot-generator.js
snapshot/android/snapshot-generator.js

The runtime will not contain snapshot tools for macOS anymore.
Related to: https://github.com/NativeScript/android-runtime/pull/1527

feat: snapshot in Docker on macOS with Android runtime 6.3.0 or higher

---

demo/AngularApp/webpack.config.js
index.js
templates/webpack.angular.js
templates/webpack.config.spec.ts

The AngularCompilerPlugin is resolving the files based on the `paths` property from the tsconfig and we have to unify the core modules package name in order to avoid duplicate modules causing app crashes on Android.
`vendor.js` contains both the `@nativescrip/core/ui/application` and the proxy `tns-core-modules/ui/application` in Angular apps with short imports support in their `tsconfig`:
```json
"paths": {
"*": [
"./node_modules/tns-core-modules/*",
"./node_modules/*"
],
"~/*": [
"app/*"
]
}
```
We are processing the `tsconfig` paths and unifying the core modules package name in order too keep a single package name in the generated code.
Related to: may failing Angular related e2e tests

fix: avoid duplicate modules from tns-core-modules and @nativescript/core

---

index.js
package.json

The `AngularCompilerPlugin` is using these paths for resolving the Webpack modules similar to the `alias` array in the other flavors.
Related to: https://github.com/NativeScript/nativescript-angular/issues/2058

fix: add missing tsconfig paths when the app is using only scoped core modules and Angular

---

lib/after-prepare.js
lib/utils.js
plugins/NativeScriptSnapshotPlugin/index.js

1) navigate to any nativescript application (e.g. an empty js app)
2) `rm -rf platforms`
3) install the nativescript-cloud extension
4) `tns login`
5) `tns cloud run android --release --key-store.... --env.snapshot`
6) `enoent` exception will be thrown.
Related to https://github.com/NativeScript/nativescript-dev-webpack/issues/1118

fix: stop looking for local snapshot artefacts when the native prepare is skipped

---

bundle-config-loader.ts
index.js
plugins/PlatformFSPlugin.ts
templates/webpack.angular.js
templates/webpack.javascript.js
templates/webpack.typescript.js
templates/webpack.vue.js
xml-namespace-loader.ts

Currently there is no way to plug a custom platform for a {N} app.
The changes allow to start Webpack-only build for custom platforms with
```bash
npx webpack --env.platform desktop --watch
```
And it will build the resources in `/platforms/${platform}/app/`
A sample platform can be https://github.com/bundyo/nativescript-platform-desktop
A sample app - https://github.com/bundyo/ns-desktop-app
Implements #1122.

feat(platforms): Add support for custom platform plugins

---

CHANGELOG.md

release: cut the 1.5.0 release

---

package.json
snapshot/android/snapshot-generator.js

fix: `The provided Android NDK is vnull while the recommended one is v21.0.6113669` error in some cases

---

bundle-config-loader.ts
index.js

`.kt` extensions are not recognized
Adds the `.kt` extension to known ones, just like `.ts`
Related to: https://github.com/NativeScript/NativeScript/issues/5379

feat: Add initial support for KotlinJS
