NativeScript/nativescript-dev-webpack

tns-xml-loader.js
=> ProxyViewContainer and Placeholder added by default

installer.js
Should be merged with: https://github.com/NativeScript/nativescript-angular/pull/680
=> feat(deps): update to @ngtools/webpack v1.2.10

bin/ns-bundle
=> fix(ns-bundle): properly get tns command

npmScriptsManager.js
=> fix: bundle scripts should invoke tns run instead of tns start

bin/ns-bundle
=> fix(ns-bundle): escape command and args when spawning child process

dependencyManager.js
This should fix the unmet peerDependency `webpack@3.0` npm warning.
=> chore: bump plugin dependencies

package.json, snapshot/android/project-snapshot-generator.js
- remove dependency to adm-zip
=> refactor: hardcode android runtime - v8 versions

mangle-excludes.js
related to https://github.com/NativeScript/NativeScript/pull/4652
=> refactor: extend mangle excludes with new listener impl classes

projectFilesManager.js, templates/vendor-platform.android.ts
Remove trailing spaces, start multiline comments with '//' and replace tabs with spaces.
fixes #250
=> style: fix linting errors for the generated vendor-platform.android

npmScriptsManager.js
This reverts commit 8bd887bd7daec94ee98f59b346ee4451baeae4d3.
=> Revert "chore: add update-ns-webpack to scripts (#346)"

demo/AngularApp/app/ninjas/ninjas.component.ts, demo/AngularApp/app/ninjas/ninjas.routes.ts
Reverts NativeScript/nativescript-dev-webpack#338
=> Revert "refactor: loadChildren to work with ~/path and ./path both relative to app/"

dependencyManager.js
This reverts commit b7f7026e69e5d9bd965062f33ca0958980dde596.
=> Revert "feat(deps): add required dependencies for sass files (#351)"

.vscode/launch.json
This will allow debuggin the AngularApp's webpack process from VSCode,
open at the root of the repo.
=> refactor(debugging): Add vscode launch options to allow debugging the webpack process

CODE_OF_CONDUCT.md, LICENSE
Changes on LICENSE and CODE_OF_CONDUCT files, made by automatic tool
=> docs: update LICENSE and CODE_OF_CONDUCT.md

lib/before-cleanApp.js, package.json
Merge after https://github.com/NativeScript/nativescript-cli/pull/3339
This fixes NativeScript/nativescript-cli#3335
Ping @sis0k0 @rosen-vladimirov
=> fix: clean snapshot artifacts on cleanApp hook

register-modules.js, xml-namespace-loader.js
follow up on #525 
demo app - https://github.com/sis0k0/custom-components-test
=> fix-next: register custom components at build time

dependencyManager.js, xml-namespace-loader.js
Demo app - https://github.com/sis0k0/custom-components-test
=> fix: register XML-only custom components

CHANGELOG.md, package.json
=> release: cut the 0.14.3 release

demo/AngularApp/webpack.config.js, demo/TypeScriptApp/webpack.config.js, projectFilesManager.js
=> fix-next(projectFilesManager): tsconfig.esm.json -> tsconfig.tns.json

lib/after-prepare.js, lib/before-prepareJS.js, lib/before-preview-sync.js, lib/before-watch.js
related to https://github.com/NativeScript/nativescript-cli/issues/3813
=> fix: start using the hmr option from the hookArgs

.npmignore
Remove some files from the npm package as they are meaningful only for development of the plugin.
Test related files and .md files specific for contribution are included in the npm package.
Test related files and .md files specific for contribution are NOT included in the npm package.
=> chore: filter some files from npm package

hot.js
A minor improvement over message formatting for unaccepted or declined HMR changes
=> refactor(hmr): improve hot decline/no-accept message

package.json
This will require us to bump them in templates as well.
=> chore: bump ng dependencies to match ns-angular

dependencyManager.js
Bump ng dependencies version to sync with nativescript-angular.
=> chore: bump ng dependencies version

xml-namespace-loader.js
Stumbled on it while debugging something else.
=> fix(xml-namespace-loader) Fix obvious argument typo

unit-testing-config-loader.js
Rel to:
https://github.com/NativeScript/nativescript-cli/issues/4477
https://github.com/NativeScript/nativescript-cli/issues/1798
=> fix: respect files property from karma.config on `tns test android --bundle` command

unit-testing-config-loader.js
=> chore: merge release into master

CHANGELOG.md, package.json
=> release: cut the 0.21.1 release

templates/webpack.vue.js
=> fix: add support for executing unit tests for vue projects (#839)

CHANGELOG.md, package.json
=> release: cut the 0.21.2 release

package.json
As we released v0.23.0 by mistake, we need to bump the version to 0.24.0
=> fix: bump version to 0.24.0

CHANGELOG.md, package.json
=> release: cut the 0.24.1 release

xml-namespace-loader.js
=> fix(xml-ns-loader): remove wrong register of xml

package.json
=> chore: bump version to 1.0.0

hmr/hmr-update.ts
Fix default export causing error.
=> fix: hmr export default crash

bundle-config-loader.ts
Fix crash caused by default export
=> fix: default export crash

package.json
=> fix: add loader-utils as dep instead of dev-dep

templates/webpack.javascript.js
> This unifies the behavior with the TypeScript, Vue and Angular flavors.
Related to: https://github.com/NativeScript/nativescript-dev-webpack/issues/983
=> fix(js): try to resolve node_modules from the project root before resolving in a linked location

CHANGELOG.md
=> release: cut the 1.0.2 release

CHANGELOG.md
=> release: cut the 1.0.3 release

package.json
=> chore: bump version to 1.2.0

CHANGELOG.md
=> release: cut the 1.1.0 release

CHANGELOG.md
=> release: cut the 1.1.1 release

package.json
=> chore: set version to 1.3.0

xml-namespace-loader.spec.ts, xml-namespace-loader.ts
The `xml-namespace-loader` fails when there is xml with platform specific namespace (ex. `<ios:GridLayout />`)
Platform specific namespaces (`ios:` and `android:`) are handled without error.
=> fix: Unbound namespace error with ios and android

CHANGELOG.md, package.json
=> release: cut the 1.2.1 release

package.json
=> chore: bump version to 1.4.0

package.json
Related to: https://github.com/NativeScript/worker-loader/issues/41
=> fix: update worker loader in order to fix HMR

index.js
Related to: https://github.com/NativeScript/nativescript-angular/issues/2058
=> fix: handle missing paths obj in tsconfig

CHANGELOG.md
=> release: cut the 1.4.1 release

dependencyManager.js
updated `@angular/compiler-cli` dependency to match dependency required by @nativescript/angular
Closes #1114
https://github.com/NativeScript/nativescript-dev-webpack/issues/1114
Dev dependency of `@angular/compiler-cli` is updated to ~8.2.0
Fixes/Implements/Closes #1114 .
=> feat(dependencies): updated `@angular/compiler-cli` dependency

package.json
In case you have multiple TypeScript workers in Angular app, trying to build the project with AOT fails. The fix is in 0.11.0 version in nativescript-worker-loader, so update it to resolve the issue.
=> fix: AOT compilation of multiple workers should work

CHANGELOG.md
Release nativescript-dev-webpack@1.5.1
=> release: cut 1.5.1 release
